## Figure 5

Analysis of Pax5 validation experiments.

Kexin Dong

Last Update: Feb 4, 2026

In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats
import seaborn as sns
import warnings
import os
import functools
import upsetplot
from adjustText import adjust_text
import matplotlib.patheffects as PathEffects

warnings.filterwarnings('ignore')
plt.rc('font', family='Helvetica')

## Process validation data

In [41]:
sample = 'Pax5'
fp = os.path.join('validation', sample)

In [43]:
flow_dict = {}
for fname in os.listdir(fp):
    if fname.endswith('.xls'):
        sample_name = fname.replace('.xls', '')
        sample_name = sample_name.replace(f'{sample}-', '')
        file_path = os.path.join(fp, fname)
        df = pd.read_excel(file_path)  
        # process df
        df = df[['Name', 'Statistic']]
        df.columns = ['Variant', '%BFP+']
        df = df[[x.endswith('BFP+') or x.endswith('REP+/GFP+') for x in df['Variant']]].reset_index(drop=True)
        df['Variant'] = df['Variant'].apply(lambda x: x.split('/')[0].split('.')[0])
        # Add Timepoint column
        df['Timepoint'] = sample_name
        # Add Treatment column
        # df['Treatment'] = 'Untreated'
        flow_dict[sample_name] = df

In [44]:
gRNA_dict = dict(zip(
    ['8524','8525','8508','8526','8498','ST','CBE Edited'],
    ['R38C','R38C','G314R','R199K','G290R','ST','CBE Edited']
))

In [45]:
flow_dict['D0']

                                            Variant  %BFP+ Timepoint
0                              Baseline_8498_C6_001   23.4        D0
1                              Baseline_8526_C2_001   23.1        D0
2                          Baseline_CBE Rep vs Edit   14.2        D0
3    Baseline_Pax5 8508 SCC3  vs CBE Rep Edited_002   22.5        D0
4    Baseline_Pax5 8508 SCC3  vs CBE Rep Edited_002   99.3        D0
5   Baseline_Pax5 8524 SCC11  vs CBE Rep Edited_001   19.5        D0
6   Baseline_Pax5 8524 SCC11  vs CBE Rep Edited_001   99.0        D0
7                 Baseline_Pax5KO vs CBE Rep Edited   81.0        D0
8         Baseline_ST CBE 16  vs CBE Rep Edited_003   24.0        D0
9         Baseline_ST CBE 16  vs CBE Rep Edited_003   98.7        D0
10                Baseline_Pax5KO vs CBE Rep Edited   81.0        D0

In [33]:
flow_dict['D0']['Variant'] = ['8498','8526','8508','8524','ST']
flow_dict['D0']['Variant'] = flow_dict['D0']['Variant'].map(gRNA_dict)
flow_dict['D0']['Replicate'] = [np.nan]*5
flow_dict['D0']['Sample'] = [np.nan]*5
flow_dict['D0']

  Variant  %BFP+ Timepoint  Replicate  Sample
0   G290R   23.4        D0        NaN     NaN
1   R199K   23.1        D0        NaN     NaN
2   G314R   22.5        D0        NaN     NaN
3    R38C   19.5        D0        NaN     NaN
4      ST   24.0        D0        NaN     NaN

In [ ]:
flow_dict['D0']['Variant'] = ['8498']*5 + ['8526']*5 + ['8498']*3 + ['8526']*3 + ['8498']*5 + ['8526']*5 + ['8498']*5 + ['8526']*5 + ['CBE_Edited']*4 + ['KO']*4 + ['ST']*4 +

In [35]:
flow_dict['D10']

                  Variant  %BFP+ Timepoint
0    Bone Marrow_8498_001   49.8       D10
1    Bone Marrow_8498_002   52.4       D10
2    Bone Marrow_8498_003   42.1       D10
3    Bone Marrow_8498_004   47.3       D10
4    Bone Marrow_8498_005   54.8       D10
..                    ...    ...       ...
106       Spleem_8508_004   54.9       D10
107       Spleem_8524_001   92.6       D10
108       Spleem_8524_002   85.7       D10
109       Spleem_8524_003   90.6       D10
110       Spleem_8524_004   89.6       D10

[111 rows x 3 columns]

In [ ]:
ABE_LFC = pd.read_csv('LFC-FDR/og/ABE_LFC_FDR_df_og.csv')
CBE_LFC = pd.read_csv('LFC-FDR/og/ABE_LFC_FDR_df_og.csv')
ABE_LFC['Editor']='ABE'
CBE_LFC['Editor']='CBE'
OG = pd.concat([ABE_LFC, CBE_LFC])

ABE_LFC_FOCUSED = pd.read_csv('LFC-FDR/focused/ABE_LFC_FDR_df_focused.csv')
CBE_LFC_FOCUSED = pd.read_csv('LFC-FDR/focused/CBE_LFC_FDR_df_focused.csv')
ABE_LFC_FOCUSED['Editor']='ABE'
CBE_LFC_FOCUSED['Editor']='CBE'
FOCUSED = pd.concat([ABE_LFC, CBE_LFC])